services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: deepthought-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    user: root
    volumes:
      - ./data/dynamodb:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000/shell/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - sn-deepthought

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: deepthought-dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=${DC_DYNAMODB_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    depends_on:
      dynamodb-local:
        condition: service_healthy
    networks:
      - sn-deepthought

networks:
  sn-deepthought:
    driver: bridge
